aws:
  access_key: xxx
  secret_key: yyy
  region: 'us-east-1'
  voice_bucket: 'hearvoice'
  transcribe_bucket: 'hearvoice-transcribed'
  trans_poll_freq: 2500
language_code: 'en-US'
sample_rate_hertz: 48000
confidence_threshold: 0.6
